import type { Metadata } from "next";
import { Tinos, Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";

const georgiaSerif = Noto_Sans_Georgian({
  variable: "--font-georgia-serif",
  subsets: ["latin"],
});
const timesNewRoman = Tinos({
  variable: "--font-times-new-roman",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${georgiaSerif.variable} ${timesNewRoman.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
